pipeline:

  load-cache:
    image: drillster/drone-volume-cache
    volumes: [/tmp:/cache]
    restore: true
    mount:
      - .gradle/caches
      - .gradle/wrapper

  build:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - cd ogcapi-stable
      - ../gradlew assemble publishToMavenLocal -PisSnapshot=true
      - cd ../ogcapi-draft
      - ../gradlew assemble -PisSnapshot=true --init-script ../.maven-local.gradle
    when:
      event: [push, pull_request]

  publish-snapshot:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - cd ogcapi-stable
      - ../gradlew publish -PisSnapshot=true -PsnapshotUser=$SNAPSHOT_USER -PsnapshotPassword=$SNAPSHOT_PASS
      - cd ../ogcapi-draft
      - ../gradlew publish -PisSnapshot=true -PsnapshotUser=$SNAPSHOT_USER -PsnapshotPassword=$SNAPSHOT_PASS --init-script ../.maven-local.gradle
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: push
      branch: master

  save-cache:
    image: drillster/drone-volume-cache
    volumes: [/tmp:/cache]
    rebuild: true
    mount:
      - .gradle/caches
      - .gradle/wrapper

  notify:
    image: plugins/slack:1.3.0
    webhook: ${SLACK_WEBHOOK}
    secrets: [ slack_webhook ]
    link_names: true
    template: >
      {{#if build.pull }}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: {{ repo.owner }}/{{ repo.name }} - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)
      {{/if}}
      Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
      Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
      Author: <@{{ build.author }}>
      Duration: {{ since build.created }}
      <{{ build.link }}|Visit build page ↗>
    when:
      status:  [ failure, success ]
