sudo: required
services:
- docker
language:
- java
jdk:
- openjdk11
node_js: '10'
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- npm install -g yarn
script:
- "./gradlew assemble"
after_success:
- "./gradlew dockerDistTar"
- cd build/docker
- export TAG=$TRAVIS_BRANCH
- docker build -t $REPO:$TAG .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO
- cd ../../ogcapi-stable
- if [[ -n "$TRAVIS_TAG" ]]; then ../gradlew publishToMavenLocal bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_PASS; fi
- cd ../ogcapi-draft
- if [[ -n "$TRAVIS_TAG" ]]; then ../gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_PASS --init-script ../.maven-local.gradle; fi
env:
  global:
  - REPO=iide/ldproxy
  - secure: VtIPErCteCfBpMHHjYZ5OsLGRoMMGfRMRA/qCh4Qus0IuwbipKsb4abAxxD4WTTG6DDPmubBz6bMreSW5uPJFSEqjYefBT70eJzVwMmrhrKd+uPSwhyH7NNUpgccnskouyFCf7H7fhGh8yIs7qnd976aFj7xF6wMHBNSXBquB/O7H/pPapClZ9VoKP9FAEldaUbskCL+a5qvjV5Lgs6rQDRJck5FxQMpeGIJpJ/Kmtrzv1CZsBTIx//wO6SrwrdbxNDsOe9363UebYvjUjZrtMGsA1GdU9EwRl0hS8crDTaVQLsXpVCctkPdtSGhGtiqskb3+GRjew3Yo/QmpV3MwhlMPyS3Cfmsg7UxjUmY2AMTsTApNlO+ZgechN/urY5pYVT+Gn/YoF5ffkDhynF0bUjqQU5kmt0DXxpT2P5jswT2hZ3tgUVCR0XKfCoqTJRW9MI7jJq9wPXjwI9ojcXyQ+5E9wUHxbr7qMZecZkMMbtLksSkmiw+72TrP/n7nkRI5xpXX1rRIuf1s5Ss5c4U1pvl9XETgRg354a6ZJEfGjcD5UHikVOZrZwbihmF9S4Y/U2qvrN+EzrNJab5dkWuqfYRo1owYuSOa14H6GdvPTK0LU3zrwt/AAiC3F2qu9l9vzLiyWy+eT+k/PkZHE6lYen6jnoZxWuZ61DmQ8rKXGs=
  - secure: mXzyNiDh10Hdclc8w+HAl+WNOOSO03kkKiyuNeNCRKhos+gwNdanfvXk20Tc4ED3oL7OGNX39OnNlgdvnSKko9d8HOcy4ZXvsyaPQtSLAEdMZark40Qpg6RyzjnAgXHd3EaBHoHtaqFnd5T1zoB7ZqMIArL5Ku78kWL9+BX1cv+PO7X6i8Hhw8Ii2XOmqmSoC1pdXgFyIyBbVziN5DeMAv0W53lVv8jOSXTFr4DgFFftDMxnhiKUuG+qQvZ+BjBNKl8st6iJID2jktgLu5hDHEHX1Pxt1816KCx8FFI81X80iBSAdKJGIs2bBa5PWNmHSKZ5rP3ZwytvDHowDV2bofkCaHNr3TTRNk7JpK/YpLR9BR595ywsVcXbdadCvQ4aO63qApA5tZSdOEu4oTYmpEyZbHZYrr1Uxi+S++NczzumNriMIjLv5iM0j67yD+8i1FlI4pCigh/ZO/XnA+RKHxlpKh9jkfMtE+eaMV/Lgto41py0AcEXv50Lz/U5LfSsxcz2m4FgfCkmyKxqsqBN7Pcu6mUuEznp6g3x/2BgNzwzETEG2TTfaIXdCmPXTYLzYQmUgJSYouUnMRTW3YvbBmSj/uLgZKl051ManFmBvOFRb9fqgQmOk4B8wtj8rK5q/AfMtLsMjuowGcN2yZSNvGGXefgMvR7WckeOdjq555w=
  - secure: X0WNrhsrt/+DZ1bBblaj+sfuf/K/adV3EPOFuImmubTkDZiZSrF0n0pFRu8tQOhtMgJXK0WRdXyLnhren/QyBazZKnIbNIG++c7BsYSMVMZWQOZT9uhTPL1uOM/Lf5ZMq+x6MSxcOiFuMJXHQmqzjaMKrsa0qdPGcZm8UKODpa5DjczRl7kJqg4CWxTPiJAQkOePwFHZyrOk3NjiVCiCFYbgv1BVnu+riUy39AZjXk2F5rwuOtCEwSY4FhHpZeGf0upDQIaN5ZnyLy2gvPeV/7Nog2KipsL//BaY6ed7YdEejJHNA0HfRBZxPg5Wkb4FQs2gzMbT2xnmMYShXGL5KzEglMWBavetzeYUvKVyhQ+aUBOty+nN6bsJClam7/EqvAcgh40pSE9J7HHguhBfdVDA4EmP+5VcZmW4pP0PQN9BTSew2+8z7K5J0+7JoMLgpevMPQccEP7MGd7KPgd04spYTqu6U1yteCbcUkwJicuPIFgQjPVuIzt6klPx6eKKUqHGf2ShnuWu0CjXauReYTNel1bkNX/hjoZDOdzJDuUzawm/quu/7f9ixZKYAjfk0pJXFsJXY8WqHaLR77DQlL7yjyd+km8/8k4fOiIH844iS0cR4/hVRkTFIsjiOUdXs1GwT62yepQzNJHWlWY58/tD4lXSq2FqoBZWL2B+Ulc=
  - secure: Bb5T1X3LsBveVrN8e8MXFiXIb0WYxq/giJLDdPvwrgRCrvFMqMxOHlTHDbPttvIIK05JxgSo+lSwcsMncBKm0ihgdGhcldUYSnHcHgHLPD5Pk5Qhba3RefqJ3AcpvTEA/hsa3XmwGYoXK8rb3nhkkHDZiZa7OEbP7V+Dv2eU/6pmp9fGDi2N3fnNNYU6uBB+oDkS/fmkOipfL/QZ1qmxDOcbEWxSS9/VSkq5T6MDUtbCbrJujGNc/qnRN/7DiKz0Ad1mPrTj6yOa89Eu1cezNOa6r/DgcLWBzo//JIuXtYE5gg/vWPzVUWuXc3KcWKhbmh/khhPe+2IYmZ11rUs8MpLTvV77MvpbjPYCrT6exPUku4tXebXJ+n6GO5bQ6xsl0LD97DvX/7O/sVBb5qkVRmpSC0Z8WeWgmlDtBSEJKgoxxS6Rm6lFuRjpP6JZfZHxB4N5LMaklEl/kD7YBselDzthP8V7ufuB/qB9PyfZf9vgqE8PXYCNetGs+ksSV0AshgML1kbHbADWRtrI69H9mm06kkWfWOw05fQVKR2bRNn11qcXRHwLFX9Q7XmHYng9pRvYi2m2Py6072NEFLGnImUYApkIPvMDjr9Z1IYCRmm1GF/Lj/YwP3qpLSDK7Yow5+mXS/it8gav3Nharhjq84XRGid1Nv9Zt/PfsrGMwAk=
