logFilters:
  - code: YN0002
    level: discard
  - code: YN0062
    level: discard

npmScopes:
  xtraplatform:
    npmAlwaysAuth: false
    npmRegistryServer: "https://dl.interactive-instruments.de/repository/npm/"

packageExtensions:
  "@neutrinojs/react@*":
    peerDependencies:
      react-hot-loader: "*"
  "@ogcapi/html@*":
    dependencies:
      eslint-import-resolver-node: "*"
      eslint-plugin-babel: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
      regenerator-runtime: "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
  feature-u@*:
    peerDependencies:
      prop-types: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
