npmScopes:
    xtraplatform:
        npmRegistryServer: 'https://dl.interactive-instruments.de/repository/npm/'
#        npmAuthToken: '${NPM_TOKEN:-not_set}'
        npmAlwaysAuth: false

packageExtensions:
    'eslint-module-utils@*':
        peerDependencies:
            'eslint': '*'
    '@storybook/addon-essentials@*':
        peerDependencies:
            '@babel/core': '*'
            webpack: '*'
    '@storybook/core@*':
        peerDependencies:
            '@storybook/addon-essentials': '*'
    '@storybook/react@*':
        peerDependencies:
            '@storybook/addon-essentials': '*'
    feature-u@*:
        peerDependencies:
            prop-types: '*'
    "@neutrinojs/react@*":
        peerDependencies:
            react-hot-loader: "*"
    '@ogcapi/html@*':
        dependencies:
            'regenerator-runtime': '*'
            'eslint-plugin-babel': '*'
            'eslint-plugin-import': '*'
            'eslint-plugin-jsx-a11y': '*'
            'eslint-plugin-react': '*'
            'eslint-plugin-react-hooks': '*'
            'eslint-import-resolver-node': '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.2.cjs
