[versions]
schema-validator = '1.5.9'
earcut4j = '2.2.2'
flatbuffers = '25.2.10'
flatgeobuf = '3.29.0'
json-patch = '2.0.2'
spdx = '2.0.5'

[libraries]
# foundation
schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "schema-validator" }
spdx = { module = "org.spdx:java-spdx-library", version.ref = "spdx" }

# gltf
earcut4j = { module = "io.github.earcut4j:earcut4j", version.ref = "earcut4j" }

# flatgeobuf
flatbuffers = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffers" }
flatgeobuf = { module = "org.wololo:flatgeobuf", version.ref = "flatgeobuf" }

# crud
json-patch = { module = "com.gravity9:json-patch-path", version.ref = "json-patch" }

[bundles]
