npmScopes:
  xtraplatform:
    npmAuthToken: "${BINTRAY_NPM_TOKEN:-not_set}"
    npmPublishRegistry: "https://api.bintray.com/npm/iide/npm/"
    npmRegistryServer: "https://api.bintray.com/npm/iide/npm/"

packageExtensions:
  feature-u@*:
    peerDependencies:
      prop-types: "*"
  "@neutrinojs/react@*":
    peerDependencies:
      react-hot-loader: "*"
    

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
