yarnPath: "C:\\dev\\ldproxy\\ogcapi-stable\\ogcapi-common\\src\\main\\javascript\\.yarn\\releases\\yarn-berry.js"
npmScopes:
  xtraplatform:
    npmRegistryServer: https://api.bintray.com/npm/iide/npm/
    npmPublishRegistry: https://api.bintray.com/npm/iide/npm/
    npmAuthToken: ${BINTRAY_NPM_TOKEN:-not_set}
packageExtensions:
  "eslint-module-utils@*":
    peerDependencies:
      "eslint": "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
  "@xtraplatform-core@*":
    dependencies:
      babel-loader: "*"
  feature-u@*:
    peerDependencies:
      prop-types: "*"
pnpMode: loose