
clone: 
  git:
    image: woodpeckerci/plugin-git
    when:
      event: tag

pipeline:

  libs:
    image: openjdk:11-slim
    commands:
      - ./gradlew publish dockerCopy -Prelease=true -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: tag

  docker:
    image: plugins/docker
    settings: 
      repo: iide/ldproxy
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: build/docker/Dockerfile
      context: build/docker
    secrets: [ docker_username, docker_password]
    when:
      event: tag

  docker-latest:
    image: plugins/docker
    settings: 
      repo: iide/ldproxy
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: build/docker/Dockerfile
      context: build/docker
    secrets: [ docker_username, docker_password]
    when:
      event: tag

# TODO: fails because java is missing ???
  github:
    image: node:12-alpine
    commands:
      - export HOME=$${CI_WORKSPACE}
      - apk --no-cache add git libc6-compat
      - wget -O - https://github.com/cli/cli/releases/download/v1.2.0/gh_1.2.0_linux_amd64.tar.gz | tar xzvf -
      - chmod +x gh_1.2.0_linux_amd64/bin/gh
      - npx github-release-notes@0.17.1 release --override --token=$GITHUB_TOKEN
      - npx github-release-notes@0.17.1 changelog --override --token=$GITHUB_TOKEN
      - git config user.name $CI_COMMIT_AUTHOR
      - git config user.email $CI_COMMIT_AUTHOR_EMAIL
      - git checkout -B changelog-$CI_COMMIT_TAG
      - git add CHANGELOG.md
      - git commit -m "add changelog for $CI_COMMIT_TAG"
      - git push -u https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$CI_REPO_NAME.git changelog-$CI_COMMIT_TAG > /dev/null 2>&1
      - GITHUB_TOKEN=$GITHUB_TOKEN ./gh_1.2.0_linux_amd64/bin/gh pr create --base master --head changelog-$CI_COMMIT_TAG --reviewer $CI_COMMIT_AUTHOR --title " add changelog for $CI_COMMIT_TAG" --body ""
    secrets: [ github_token, github_user ]
    when:
      event: tag
