
clone: 
  git:
    image: woodpeckerci/plugin-git
    when:
      event: [ push, tag ]

pipeline:
  dtrack:
    image: eclipse-temurin:11
    commands:
      - ./gradlew publishSbom -PdtrackApiUrl=https://dtrack.ldproxy.net/api/v1/bom -PdtrackApiKey=$DTRACK_API_KEY
    secrets: [ dtrack_api_key ]
    when:
      event: [ push ]
      branch: [ master, maintenance-* ]

  dtrack-release:
    image: eclipse-temurin:11
    commands:
      - ./gradlew publishSbom -Prelease=true -PdtrackApiUrl=https://dtrack.ldproxy.net/api/v1/bom -PdtrackApiKey=$DTRACK_API_KEY
    secrets: [ dtrack_api_key ]
    when:
      event: [ tag ]

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release upload $CI_COMMIT_TAG "build/reports/sbom.json#CycloneDX SBOM"
    secrets: [ github_token ]
    when:
      event: [ tag ]

