when:
  event: push

steps:

  libs:
    image: eclipse-temurin:11
    environment:
      - DOCS_VERSION=next
    commands:
      - ./gradlew publish dockerContext docsVuepress -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]

  docs:
    image: williamjackson/netlify-cli
    environment:
      - XDG_CONFIG_HOME=/home/node
    commands:
      - netlify deploy --prod --auth $NETLIFY_TOKEN --site 61d8c25c-3ee2-4cc5-85a6-431afba9b9b5 --message "$CI_COMMIT_MESSAGE" --dir $CI_WORKSPACE/build/markdown/docs/.vuepress/dist/
    secrets: [ netlify_token]
    when:
      branch: master

  dist-arm64:
    image: eclipse-temurin:11
    commands:
      - ./gradlew dockerContext -Pplatform=linux-arm64 -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]

  docker:
    image: docker.ci.interactive-instruments.de/cicd/drone-docker-buildx
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: docker.ci.interactive-instruments.de
      repo: docker.ci.interactive-instruments.de/iide/ldproxy
      tags: ${CI_COMMIT_BRANCH}
      force_tag: true
      dockerfile: build/docker/Dockerfile
      context: build/docker
      pull_image: true
      platforms:
        - linux/amd64
        - linux/arm64

  docker-hub:
    image: docker.ci.interactive-instruments.de/cicd/drone-docker-buildx
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      repo: iide/ldproxy
      tags: next
      force_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: build/docker/Dockerfile
      context: build/docker
      pull_image: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      branch: master
