
clone: 
  git:
    image: woodpeckerci/plugin-git
    when:
      event: push

pipeline:

  libs:
    image: openjdk:11-slim
    commands:
      - ./gradlew publish dockerDistTar -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$SNAPSHOT_USER -PdeployPassword=$SNAPSHOT_PASS
    secrets: [ snapshot_user, snapshot_pass]
    when:
      event: push

  docker:
    image: plugins/docker
    settings:
      registry: docker.ci.interactive-instruments.de
      repo: docker.ci.interactive-instruments.de/iide/ldproxy
      tags: ${CI_COMMIT_BRANCH}
      force_tag: true
      dockerfile: build/docker/Dockerfile
      context: build/docker
      pull_image: true
    when:
      event: push

# TODO: is this triggered on PR merge?
  docker-hub:
    image: plugins/docker
    settings:
      repo: iide/ldproxy
      tags: next
      force_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: build/docker/Dockerfile
      context: build/docker
      pull_image: true
    secrets: [ docker_username, docker_password]
    when:
      event: push
      branch: master